"""empty message

Revision ID: b42b5518ca60
Revises: 
Create Date: 2024-12-18 20:59:52.954835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b42b5518ca60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('service_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('Cambio de Aceite y filtro', 'Alineación y Balanceo', 'Rotación de Neumáticos', 'Mecanica Ligera', name='name'), nullable=True),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.Column('cost', sa.Enum('$1.500', '$12.000', '$4.000', '$8.000', name='cost'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.Enum('client', 'admin', name='user_type'), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('social_reason', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('ci_rut', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=30), nullable=True),
    sa.Column('model', sa.String(length=30), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('license_plate', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_ID', sa.Integer(), nullable=False),
    sa.Column('Service_Type_ID', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Agendado', 'Ingresado', 'En Proceso', 'Finalizado', name='name'), nullable=True),
    sa.Column('Start_Date', sa.String(length=30), nullable=True),
    sa.Column('End_Date', sa.String(length=30), nullable=True),
    sa.Column('Total_Cost', sa.String(length=50), nullable=True),
    sa.Column('Payment_status', sa.String(length=30), nullable=True),
    sa.Column('User_ID', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['Service_Type_ID'], ['service_type.id'], ),
    sa.ForeignKeyConstraint(['User_ID'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vehicle_ID'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sale_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Service_ID', sa.Integer(), nullable=True),
    sa.Column('Text', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['Service_ID'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parts_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Service_ID', sa.Integer(), nullable=True),
    sa.Column('Parts_ID', sa.Integer(), nullable=True),
    sa.Column('Quantity', sa.Integer(), nullable=True),
    sa.Column('Cost', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['Parts_ID'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['Service_ID'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('User_ID', sa.Integer(), nullable=True),
    sa.Column('Vehicle_ID', sa.Integer(), nullable=True),
    sa.Column('Date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('Service_ID', sa.Integer(), nullable=True),
    sa.Column('Status', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['Service_ID'], ['services.id'], ),
    sa.ForeignKeyConstraint(['User_ID'], ['user.id'], ),
    sa.ForeignKeyConstraint(['Vehicle_ID'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule')
    op.drop_table('parts_service')
    op.drop_table('notes')
    op.drop_table('vehicle_sales')
    op.drop_table('services')
    op.drop_table('vehicles')
    op.drop_table('user')
    op.drop_table('service_type')
    op.drop_table('parts')
    # ### end Alembic commands ###
