"""empty message

Revision ID: fa6bfeffd4b6
Revises: b42b5518ca60
Create Date: 2024-12-18 20:59:57.012680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6bfeffd4b6'
down_revision = 'b42b5518ca60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_type', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(),
               type_=sa.Enum('Cambio de Aceite y filtro', 'Alineación y Balanceo', 'Rotación de Neumáticos', 'Mecanica Ligera', name='name'),
               existing_nullable=True)

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(),
               type_=sa.Enum('Agendado', 'Ingresado', 'En Proceso', 'Finalizado', name='name'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('Agendado', 'Ingresado', 'En Proceso', 'Finalizado', name='name'),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('service_type', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.Enum('Cambio de Aceite y filtro', 'Alineación y Balanceo', 'Rotación de Neumáticos', 'Mecanica Ligera', name='name'),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###
